- name: Gather system info
  hosts: all
  gather_facts: yes

  tasks:
    - name: Generate info file
      template:
        src: playbooks/templates/get_info.j2
        dest: /tmp/system_info_{{ ansible_hostname }}.yaml

    - name: Copy info file to the host node
      fetch:
        src: /tmp/system_info_{{ ansible_hostname }}.yaml
        dest: ./system_info_{{ ansible_hostname }}.yaml
        flat: yes