---
- name: Gather system information and create a structured file
  hosts: all
  gather_facts: true
  tasks:
    - name: Create system info file on the controller machine
      ansible.builtin.template:
        src: ../templates/system_info.j2
        dest: "../system_info_{{ inventory_hostname }}.yml"
      delegate_to: localhost
