version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: balance-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sa
      - sb

  sa:
    build:
      context: ./sa
    container_name: sa
    ports:
      - "8081:80"

  sb:
    build:
      context: ./sb
    container_name: sb
    ports:
      - "8082:80"
