version: '3.9'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    networks:
      - my_network
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - sa
      - sb

  sa:
    build:
      context: ./sa
    container_name: sa
    ports:
      - "8081:80"
    networks:
      - my_network

  sb:
    build:
      context: ./sb
    container_name: sb
    ports:
      - "8082:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
