---
- name: Create docker-compose
  template:
    src: docker-compose.yml.j2
    dest: /home/roman/acs/lab3/ansible/docker-compose.yml

- name: Run Conts by docker-compose
  community.docker.docker_compose_v2:
    project_src: /home/roman/acs/lab3/ansible
    state: present